### PR TITLE
fix lm-1568

### PR DESCRIPTION
**Pull request by KhanhNH9**
## PR Checklist
 * Which ticket is this associated with?
    * Closes #LM-1568
 * Description
    * Remove authToken in payload
    * Add userId in payload

### CODE REVIEW

**Review by trungpv3 — APPROVED** [review]

**Comment by davegines** [comment]
@trungpv3 can you add a change log entry https://github.com/RentDynamics/rentdynamics-js/blob/master/CHANGELOG.md

Thanks

**Comment by Belax8** [comment]
Can you also update the package.json to show the updated version number?

**Review by davegines — CHANGES_REQUESTED** [review]
I spoke with @Belax8 about this and this may not work as expected. I will let him work with you on this.

**Comment by KhanhNH9** [comment]
updated version in package.json

**Review by Belax8 — CHANGES_REQUESTED** [review]
The logout is already working as expected. We can close this PR. I'll add more details to the ticket.

**Pull request closed without merging**
